# Generated by Django 3.0.8 on 2020-12-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=50)),
                ('birth_date', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=50)),
                ('programming_lang', models.CharField(max_length=200)),
                ('current_ctc', models.CharField(max_length=100)),
                ('expect_ctc', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
