# Generated by Django 3.0.8 on 2020-12-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(max_length=100),
        ),
    ]
